// Writes the build stamp as a module the service worker imports statically.
//
// A stamp read back with fetch() lies: it comes off disk, so a browser running
// cached service-worker bytes still reports the newest build. Imported into the
// worker, the value travels with whatever bytes are actually running.
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';

const stamp = new Date().toISOString();
const out = fileURLToPath(new URL('../extension/build-stamp.js', import.meta.url));
fs.writeFileSync(out, `// Generated by scripts/stamp-build.mjs; do not edit.\nexport const BUILD = '${stamp}';\n`);
fs.writeFileSync(
  fileURLToPath(new URL('../extension/build-stamp.json', import.meta.url)),
  JSON.stringify({ builtAt: stamp }, null, 2) + '\n',
);
console.log('build stamp', stamp);
